name: Build and Deploy Python App to Azure Web App

env:
  AZURE_WEBAPP_NAME: segmentationimages
  PYTHON_VERSION: '3.9'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m venv myenv
          .\myenv\Scripts\activate
          pip install -r requirements.txt

      - name: Clean up virtual environment and unnecessary files
        run: |
          rm -rf myenv  # Supprimer l'environnement virtuel
          rm -rf *.log  # Supprimer les fichiers de log
          rm -rf __pycache__  # Supprimer les fichiers de cache Python
          rm -rf tmp/  # Supprimer les fichiers temporaires

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
